/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UPCore Club Tracker API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Returns the list of clubs being tracked with their settings
 * @summary Get all tracked clubs
 */
export const GetTrackedClubsResponseItem = zod.object({
  id: zod.string(),
  tag: zod.string(),
  name: zod.string(),
  loggingEnabled: zod.boolean(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const GetTrackedClubsResponse = zod.array(GetTrackedClubsResponseItem);

/**
 * @summary Add a club to tracking
 */
export const AddTrackedClubBody = zod.object({
  tag: zod.string(),
  name: zod.string(),
});

/**
 * @summary Remove a club from tracking
 */
export const RemoveTrackedClubParams = zod.object({
  tag: zod.coerce.string(),
});

/**
 * @summary Toggle logging for a club
 */
export const ToggleClubLoggingParams = zod.object({
  tag: zod.coerce.string(),
});

export const ToggleClubLoggingBody = zod.object({
  loggingEnabled: zod.boolean(),
});

export const ToggleClubLoggingResponse = zod.object({
  id: zod.string(),
  tag: zod.string(),
  name: zod.string(),
  loggingEnabled: zod.boolean(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Get live club overview from Brawl Stars API
 */
export const GetClubOverviewParams = zod.object({
  tag: zod.coerce.string(),
});

export const GetClubOverviewResponse = zod.object({
  tag: zod.string(),
  name: zod.string(),
  description: zod.string().nullish(),
  type: zod.string().nullish(),
  trophies: zod.number(),
  requiredTrophies: zod.number().nullish(),
  badgeId: zod.number().nullish(),
  memberCount: zod.number(),
  president: zod.string().nullish(),
  members: zod.array(
    zod.object({
      tag: zod.string(),
      name: zod.string(),
      role: zod.string(),
      trophies: zod.number(),
      nameColor: zod.string().nullish(),
      iconId: zod.number().nullish(),
    }),
  ),
});

/**
 * @summary Get overview for all tracked clubs
 */
export const GetAllClubsOverviewResponseItem = zod.object({
  tag: zod.string(),
  name: zod.string(),
  description: zod.string().nullish(),
  type: zod.string().nullish(),
  trophies: zod.number(),
  requiredTrophies: zod.number().nullish(),
  badgeId: zod.number().nullish(),
  memberCount: zod.number(),
  president: zod.string().nullish(),
  members: zod.array(
    zod.object({
      tag: zod.string(),
      name: zod.string(),
      role: zod.string(),
      trophies: zod.number(),
      nameColor: zod.string().nullish(),
      iconId: zod.number().nullish(),
    }),
  ),
});
export const GetAllClubsOverviewResponse = zod.array(
  GetAllClubsOverviewResponseItem,
);

/**
 * @summary Get club activity logs
 */
export const GetLogsQueryParams = zod.object({
  club: zod.coerce.string().optional().describe("Filter by club tag"),
  eventType: zod
    .enum(["join", "leave", "kick", "promotion", "demotion", "role_change"])
    .optional()
    .describe("Filter by event type"),
  search: zod.coerce.string().optional().describe("Search by player name"),
  dateFrom: zod.coerce
    .string()
    .optional()
    .describe("Filter logs from this ISO date"),
  dateTo: zod.coerce
    .string()
    .optional()
    .describe("Filter logs up to this ISO date"),
  limit: zod.coerce
    .number()
    .optional()
    .describe("Maximum number of logs to return"),
  offset: zod.coerce.number().optional().describe("Pagination offset"),
});

export const GetLogsResponse = zod.object({
  logs: zod.array(
    zod.object({
      id: zod.string(),
      clubTag: zod.string(),
      clubName: zod.string(),
      playerTag: zod.string(),
      playerName: zod.string(),
      eventType: zod.enum([
        "join",
        "leave",
        "kick",
        "promotion",
        "demotion",
        "role_change",
      ]),
      roleFrom: zod.string().nullish(),
      roleTo: zod.string().nullish(),
      timestamp: zod.string(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Get log statistics summary
 */
export const GetLogsSummaryResponse = zod.object({
  totalLogs: zod.number(),
  todayLogs: zod.number(),
  joinCount: zod.number(),
  leaveCount: zod.number(),
  kickCount: zod.number(),
  promotionCount: zod.number(),
  demotionCount: zod.number(),
  roleChangeCount: zod.number(),
  recentActivity: zod.array(
    zod.object({
      id: zod.string(),
      clubTag: zod.string(),
      clubName: zod.string(),
      playerTag: zod.string(),
      playerName: zod.string(),
      eventType: zod.enum([
        "join",
        "leave",
        "kick",
        "promotion",
        "demotion",
        "role_change",
      ]),
      roleFrom: zod.string().nullish(),
      roleTo: zod.string().nullish(),
      timestamp: zod.string(),
    }),
  ),
});
